apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sjbroughton-com-tls
spec:
  secretName: sjbroughton-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sjbroughton.com
  dnsNames:
    - sjbroughton.com
    - www.sjbroughton.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sjbroughton.com
          - www.sjbroughton.com